Script started on 2015年03月16日 (週一) 18時49分20秒
]0;F24011140@2015cpp: ~/lab1F24011140@2015cpp:~/lab1$ whoami; pwd
F24011140
/home/F24011140/lab1
]0;F24011140@2015cpp: ~/lab1F24011140@2015cpp:~/lab1$ git config =l[K[K-l
user.name=yihho
user.email=F24011140@mail.ncku.edu.tw
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=https://github.com/yihho/lab1.git
branch.master.remote=origin
branch.master.merge=refs/heads/master
remote.lab1.script.url=https://github.com/yihho/lab1.git
remote.lab1.script.fetch=+refs/heads/*:refs/remotes/lab1.script/*
]0;F24011140@2015cpp: ~/lab1F24011140@2015cpp:~/lab1$ git clone https://github.com/yihhoyihho[K[K[K[K[K/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
]0;F24011140@2015cpp: ~/lab1F24011140@2015cpp:~/lab1$ exit

Script done on 2015年03月16日 (週一) 18時51分48秒
